spring:
  application:
    name: automation-bot
  servlet:
    multipart:
      max-file-size: 50MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/automation_bot
    username: root
    password: Rajeev9934@#

server:
  port: 8085
